# Directories to exclude
exclude-dirs:
  - SOMETHING

# Files to exclude
exclude-files:
  - README.md
  - .gitignore
  - .pre-commit-config.yaml
  - LICENSE

# Add github urls
community-templates:
  - https://github.com/projectdiscovery/nuclei-templates
  - https://github.com/testtt3424/nuclei-templates
  - https://github.com/0XParthJ/Nuclei-Templates
  - https://github.com/0x727/ObserverWard_0x727
  - https://github.com/0xAwali/Blind-SSRF
  - https://github.com/0xAwali/Virtual-Host.git
  - https://github.com/1in9e/my-nuclei-templates
  - https://github.com/1oid/AnyPocsYamlParser.git
  - https://github.com/5cr1pt/templates
  - https://github.com/ARPSyndicate/kenzer-templates
  - https://github.com/Akokonunes/Private-Nuclei-Templates
  - https://github.com/AshiqurEmon/nuclei_templates
  - https://github.com/AshiqurEmon/nuclei_templates.git
  - https://github.com/BeRserKerSec/CVE-2021-26084-Nuclei-template
  - https://github.com/CharanRayudu/Custom-Nuclei-Templates
  - https://github.com/Charseki/nuclei_templates
  - https://github.com/CriticalMatterial/NucleiTemplates
  - https://github.com/Elsfa7-110/mynuclei-templates
  - https://github.com/Harish4948/Nuclei-Templates
  - https://github.com/MR-pentestGuy/nuclei-templates
  - https://github.com/Micr067/nuclei-templates
  - https://github.com/MikeeI/nuclei-templates
  - https://github.com/Mr219/nuclei_templates
  - https://github.com/NitinYadav00/My-Nuclei-Templates
  - https://github.com/R-s0n/Custom_Vuln_Scan_Templates
  - https://github.com/Saimonkabir/Nuclei-Templates
  - https://github.com/Saptak9983/Nuclei-Template
  - https://github.com/SecTheBit/CVE-2022-1388
  - https://github.com/ShangRui-hash/my-nuclei-templates
  - https://github.com/Str1am/my-nuclei-templates
  - https://github.com/Str1am/my-nuclei-templates/tree/main/MyPoc
  - https://github.com/System00-Security/backflow
  - https://github.com/V0idC0de/dir-listing-iis-test
  - https://github.com/adampielak/nuclei-templates
  - https://github.com/alexrydzak/rydzak-nuclei-templates
  - https://github.com/arielril/nuclei-templates
  - https://github.com/ayadim/nuclei-templates
  - https://github.com/bjhulst/nuclei-custom-templates
  - https://github.com/blazeinfosec/nuclei-templates
  - https://github.com/brinhosa/brinhosa-nuclei-templates
  - https://github.com/bufferbandit/gitScanNucleiTemplate
  - https://github.com/c-sh0/nuclei_templates
  - https://github.com/c0rv4x/scanfactory-nuclei-templates
  - https://github.com/c3l3si4n/malicious_nuclei_templates
  - https://github.com/clarkvoss/Nuclei-Templates
  - https://github.com/compr00t/nuclei-templates
  - https://github.com/d3sca/Nuclei_Templates
  - https://github.com/daffainfo/my-nuclei-templates
  - https://github.com/danielmofer/nuclei_templates
  - https://github.com/dk4trin/templates-nuclei
  - https://github.com/ekinsb/Nuclei-Templates
  - https://github.com/emadshanab/Nuclei-Templates-Collection
  - https://github.com/emadshanab/nuclei-templates
  - https://github.com/esetal/nuclei-bb-templates
  - https://github.com/ethicalhackingplayground/erebus
  - https://github.com/ethicalhackingplayground/erebus-templates
  - https://github.com/foulenzer/foulenzer-templates
  - https://github.com/geeknik/nuclei-templates-1
  - https://github.com/geeknik/the-nuclei-templates
  - https://github.com/glyptho/templatesallnuclei
  - https://github.com/im403/nuclei-temp
  - https://github.com/javaongsan/nuclei-templates
  - https://github.com/justmumu/SpringShell
  - https://github.com/kabilan1290/templates
  - https://github.com/kh4sh3i/CVE-2022-23131
  - https://github.com/lliwi/nuclei-repo-hunter
  - https://github.com/manasmbellani/nuclei-templates
  - https://github.com/marcositu/nuclei-custom-templates
  - https://github.com/medbsq/ncl
  - https://github.com/meme-lord/Custom-Nuclei-Templates
  - https://github.com/mertugur/nuclei-templates
  - https://github.com/michaelklaan/my-nuclei-templates
  - https://github.com/michaelklaan/nuclei-templates
  - https://github.com/n1f2c3/mytemplates
  - https://github.com/notnotnotveg/nuclei-custom-templates
  - https://github.com/obreinx/nuceli-templates
  - https://github.com/optiv/mobile-nuclei-templates
  - https://github.com/p3n73st3r/Nuclei-Templates
  - https://github.com/panch0r3d/nuclei-templates
  - https://github.com/peanuth8r/Nuclei_Templates
  - https://github.com/pikpikcu/my-nuclei-templates
  - https://github.com/pikpikcu/nuclei-templates
  - https://github.com/ping-0day/templates
  - https://github.com/praetorian-inc/chariot-launch-nuclei-templates
  - https://github.com/projectdiscovery/nuclei-templates
  - https://github.com/projectdiscovery/nuclei-templates.git
  - https://github.com/rafaelcaria/Nuclei-Templates
  - https://github.com/rafaelwdornelas/my-nuclei-templates
  - https://github.com/rahulkadavil/nuclei-templates
  - https://github.com/randomstr1ng/nuclei-sap-templates
  - https://github.com/redteambrasil/nuclei-templates
  - https://github.com/ree4pwn/my-nuclei-templates
  - https://github.com/sadnansakin/my-nuclei-templates
  - https://github.com/securitytest3r/nuclei_templates_work
  - https://github.com/sharathkramadas/k8s-nuclei-templates
  - https://github.com/shifa123/detections
  - https://github.com/shifa123/nuclei-templates-all
  - https://github.com/sickwell/nuclei-templates
  - https://github.com/smaranchand/nuclei-templates
  - https://github.com/sobinge/nuclei-templates
  - https://github.com/souzomain/mytemplates
  - https://github.com/sudo-jtcsec/public-nuclei-templates
  - https://github.com/sushant-kamble/mynuclei-template
  - https://github.com/tedmdelacruz/custom-nuclei-templates
  - https://github.com/test502git/log4j-fuzz-head-poc
  - https://github.com/th3r4id/nuclei-templates
  - https://github.com/thebrnwal/Content-Injection-Nuclei-Script
  - https://github.com/thelabda/nuclei-templates
  - https://github.com/themastersunil/Nuclei-TamplatesBackup.git
  - https://github.com/toramanemre/apache-solr-log4j-CVE-2021-44228
  - https://github.com/toramanemre/log4j-rce-detect-waf-bypass
  - https://github.com/trickest/log4j
  - https://github.com/vishal12300/all_nuclei_templatess
  - https://github.com/vysecurity/nuclei-templates-notags
  - https://github.com/wasp76b/nuclei-templates
  - https://github.com/wr00t/templates
  - https://github.com/yavolo/nuclei-templates
  - https://github.com/z3bd/nuclei-templates
  - https://github.com/zinminphyo0/KozinTemplates
